{% set name = "mleap" %}
{% set version = "0.23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5cdd1a61822a6444998a864cfd7ad72dacaeb4f483418d626219ae4c8d02b13

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.8.2
    - pandas >=0.18.1
    - python >={{ python_min }}
    - scikit-learn ~=1.0.0
    - scipy >=0.13.0b1
    - six >=1.10.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - mleap
    - mleap.bundle
    - mleap.sklearn
    - mleap.sklearn.decomposition
    - mleap.sklearn.ensemble
    - mleap.sklearn.extensions
    - mleap.sklearn.feature_extraction
    - mleap.sklearn.preprocessing
    - mleap.sklearn.tree

about:
  home: https://github.com/combust/mleap/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLeap Python API

extra:
  recipe-maintainers:
    - xhochy
